### ISSUE TITLE
Line 45 and 47 in main.py

### ISSUE THREAD

**Issue by allenwsh82** [Dhairya10/facenet-openvino#2]
Hello Expert,

For this line 45 and 47 which directory should I be pointing to in the main.py?

## TODO : Add the model path
Is this pointing to the facenet_keras.h5' in my local directory?
## TODO : Add the library path
Which library in OpenVINO should I be pointing to?

Thanks

**Comment by Dhairya10** [comment]
Hi allenwsh82,

* Line 45 - Add the OpenVINO face detection model path
* Line 47 - You can simply pass None, it will be automatically inferred according to the device you are using (CPU, GPU, etc)
